name: bloctemplate
description: A new Flutter project.

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1


  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  google_fonts: ^2.1.0
  very_good_analysis: ^2.3.0
  lint: ^1.8.2
  shared_preferences: ^2.0.13
  firebase_messaging: ^11.2.10
  flutter_local_notifications: ^9.4.0
  uuid: ^3.0.6
  cloud_firestore: ^3.1.10
  json_serializable: ^6.1.4
  google_maps_flutter: ^2.1.2
  device_info_plus: ^3.2.2
  intl: ^0.17.0
  firebase_dynamic_links: ^3.0.0
  url_launcher: ^6.0.20
  flutter_launcher_icons: ^0.9.2
  go_router: ^3.0.4
  formz: ^0.4.1



dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter

  mocktail: ^0.2.0

  flutter_native_splash: ^2.0.4

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo_small.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

