name: bloctemplate
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
#  authentication_repository:
#    path: packages/authentication_repository
  bloc: any
  equatable: any
  flutter_bloc: any


  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: any
  form_inputs:
    path: packages/form_inputs
  google_fonts: any
  very_good_analysis: any
  lint: any
  shared_preferences: any
  firebase_messaging: any
  flutter_local_notifications: any
  uuid: any
  json_serializable: any
  google_maps_flutter: any
  device_info_plus: any
  intl: any
  firebase_dynamic_links: ^4.2.5
  url_launcher: any
  flutter_launcher_icons: any
  go_router: any
  formz: any
  firebase_auth_repository:
    git:
      url: https://github.com/BartWesthoff/packages
      path: packages/firebase_auth_service
  firestore_service:
    git:
      url: https://github.com/BartWesthoff/packages
      path: packages/firestore_service

  firebase_storage: any



dev_dependencies:
  bloc_test: any
  flutter_test:
    sdk: flutter

  mocktail: any

  flutter_native_splash: any

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo_small.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

